### ISSUE TITLE
Inventory duplicate

### ISSUE THREAD

**Issue by Henry5K** [nhanaz-pm-pl/KeepInventory#8]
When you death, your Inventory duplicate, a half to victim and a half to assassin
My config:
```yaml
---
# KeepInventory Mode
#  true : Prevents players from losing items on death
#  false : Players from losing items on death
KeepInventory: true

# all : All worlds will be affected by KeepInventory Mode
# whitelist : All worlds listed below will be affected by KeepInventory Mode
# blacklist : All worlds not listed below will be affected by KeepInventory Mode
Mode: all
Worlds: []
# Worlds: ["Plots", "Arena"]

# Message to players if their inventory is safe
MsgAfterDeathTrue: "You died, but your inventory is safe!"

# Message to players if their inventory is not safe
MsgAfterDeathFalse: "You died and your inventory is not safe!"

# none : No messages have been sent to the player
# message : Sends a direct chat message to a player
# title : Send a title text to the user's screen
# popup : Sends a popup message to the player
# tip : Sends a tip message to the player
# actionbar : Send a small text to the user's screen
# MsgType: none
...
```
